### PR TITLE
Talk to cocktaildb

### PR DESCRIPTION
**Pull request by wcmitchell**
Adding some init cocktaildb endpoints

### CODE REVIEW

**Review by aleccohan — COMMENTED** [review]
Hey @wcmitchell!  I seem to be having some trouble with sending requests to the cocktaildb when sending a GET request through local deployment

> http://localhost:5000/drinks?spirit=whiskey

`  File "/Users/alcohan/.local/share/virtualenvs/sea-bass-Yc7OiHfK/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/Users/alcohan/.local/share/virtualenvs/sea-bass-Yc7OiHfK/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'www.thecocktaildb.com/api/json/v1/1/filter.php?i=whiskey': No schema supplied. Perhaps you meant http://www.thecocktaildb.com/api/json/v1/1/filter.php?i=whiskey?`

I was able to resolve this however by replacing the **www.** in front of the coctaildb url to be **http://**

**Comment by wcmitchell** [comment]
Crap, you're right! Thanks for catching that @aleccohan!

**Comment by SteveHNH** [comment]
LGTM

**Review by SteveHNH — APPROVED** [review]

**Review by aleccohan — COMMENTED** [review]
@wcmitchell TY!  Also so sorry I think I found one other tiny thing (Sorry i'm being picky :( )

it looks like the result for `/drinks` and `/spec` are not returning as json.  But!  It looks like if you wrap the response in json.dumps() that should do the trick!

Response(response=result, mimetype='application/json') ---> Response(response=json.dumps(result), mimetype='application/json')

**Review by aleccohan — APPROVED** [review]
LGTM!

**Pull request merged**
